### ISSUE TITLE
NOTICE file should be updated to conform Apache 2.0 requirements

### ISSUE THREAD

**Issue by romanjoe** [mcu-tools/mcuboot#1030]
Our legal department in Infineon Technologies found out, that current version of NOTICE file does not conform to an Apache 2.0 requirements. In particular with this paragraph https://www.apache.org/licenses/LICENSE-2.0.txt - 4 (d):

**Briefly:**
Apache 2.0 has a requirement that when additional licenses/copyrights are present in the source code then a
NOTICE file listing those licenses/copyrights is present. There is such a file for MCUBoot (see
here), but the licensees/copyright holders listed is incomplete.

There should at least be
references to Nordic Semiconductor, Cypress Semiconductor and perhaps others.

Can someone comment on this please, as i am not very familiar with licensing aspects.

**Comment by d3zd3z** [comment]
The NOTICE file is a relic from when this was part of an apache project. Unfortunately, I'm not sure if we can remove it, because code was contributed while it was present. Feel free to add your copyright to this file if you guys feel it is important. Ideally, I'd like to remove the file entirely, but that would require acknowledgment from entities that don't exist any more.

Another option would be to generate the file from copyright statements in the source.
