### ISSUE TITLE
Per image support for sign/encryption keys

### ISSUE THREAD

**Issue by utzig** [mcu-tools/mcuboot#548]
Currently MCUBoot is only able to work with a single encryption key, and multiple signing keys that could be used to validate any image.

For security purposes it would be interesting to lock specific keys per image, eg, first image set uses signing key A and encryption key B, while second image set uses signing key X and encryption key Y. This requires adding support for multiple encryption keys, and a mechanism to force keys per image, eg to avoid using signing key X to validate image set 1.

**Comment by Laczen** [comment]
@utzig, I think this is not needed.

At the moment mcuboot supports one bootloader private key (not an encryption key) and multiple public keys for the validation of signatures. The encryption key is different for each image. It starts from a new random key generated during encryption. From this random key a shared secret between the bootloader and the root is generated (using either the root public key and the bootloader private key resp. the root private key and the bootloader public key). This shared secret is than passed to a key derivation function to get the real encryption key (because the shared secret is not random enough). The bootloader and root use the same key derivation function so they can generate the same encryption key. At least this is how it should work for ec256.

This way each image has its own random encryption key and there is no need for multiple bootloader private keys. In the case of multiple root public keys the correct public key can be selected as its the one that validates the signature.
