### ISSUE TITLE
swap-move where sector sizes are multiples

### ISSUE THREAD

**Issue by archseer** [mcu-tools/mcuboot#816]
We unfortunately have a chip that uses 8kb sectors for its internal storage, but our external flash has 4kb sectors.

swap-move validates that both slots have the same number of sectors (& that the sizes match):

https://github.com/JuulLabs-OSS/mcuboot/blob/301e9755bd2490b8c25e7ab9fc5a168703ec6c63/boot/bootutil/src/swap_move.c#L211-L250

Would it be possible to adjust the implementation to allow multiples? Or is that not desirable because of firmware size increase? Alternatively we were considering just specifying both sector sizes as 8kb and accounting for that inside `flash_map` for the secondary slot.

**Comment by utzig** [comment]
It might be possible, I did not give it much thought because of the extra complexity of having to manage pairs (or double-pairs, etc) of sectors against other sectors. The original swap implementation (using scratch) does support non matching sectors, because the size of the scratch partition dictates how other sectors are moved around, so you can still fallback to creating a small scratch area and disabling the swap with move strategy.
